language: node_js
node_js:
- 13
script: "$PWD/tools/scripts/test.sh"
deploy:
  provider: npm
  email: julien@graziano.fr
  api_key:
    secure: ppE8azx8tcMwur9yyrCv2H8TuwVdrNlP6f5vjvdY4IwmeBdxjQks4lo6isNRz2n/McFSm9ZjzCSKDmagppiRCzXBQEdaTSoBfVATOplav+w9zOuZANBdkLV4bxO0mijaVJHRslBdQQsDHiShjuSBeyBGwzqo4tTbDLJ9r3r2RXWm/FB7kbAqeQnEVuMD/SOJbJAJv7//kD5coIeC3fZR6TanJtNEAO6ulTFwiMgJhbGDDTOTCuYjzfjU7E6lYeSNVJzGFIkqmD6PNkbLu50fejmpqA2CU8ZtCrvpUfxahcau/ueO0llVRIj9csqV8o3uPwwrZyMxHuCftGWaqvCTem7Qa9bT77E1768G+vAJeL5o6z2UW04P+ZnaPJEycZ10wPiUa2fNkguHTf5wkCCvZqT0E+0XxKE2hM/51ZNdGUiEJAOGD82QVPaAOMw5MRD+1xGSBI0b3ZdzrdCEjoOYqvz2nwDhL5tbbSCI+BPKkvtWA1FnGJ5q93BoxsCDXR/icAuTBx/hOI1QbmKtYP9Pu6EBpqdUOXbfQXoslYvfp8K93IGum3un4lTsVA7R4at+7M4u8ABgG6tnhXbabjjvBwfKGkyRgbWpcFt4LXIyt+n2gs4DnIgyI+1+tKTK1vXK4bGaGIJ+Wbd73nesy2p8VqvRrin79heFyYF6cRmreJk=
